"""add hashed consume token to drops table

Revision ID: 2f4be9ced90e
Revises: 536bc3b26eb2
Create Date: 2026-09-24 19:50:32.717918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4be9ced90e'
down_revision: Union[str, Sequence[str], None] = '536bc3b26eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('consume_token_hash', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drops', 'consume_token_hash')
    # ### end Alembic commands ###
