"""add encryption protocol version to drops table

Revision ID: 536bc3b26eb2
Revises: 9e9c4d4637d2
Create Date: 2026-09-20 09:35:42.919808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '536bc3b26eb2'
down_revision: Union[str, Sequence[str], None] = '9e9c4d4637d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drops', sa.Column('crypto_version', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drops', 'crypto_version')
    # ### end Alembic commands ###
