"""add index to expires_at

Revision ID: e04bb8f696a2
Revises: 2f4be9ced90e
Create Date: 2026-09-26 22:44:14.920116

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e04bb8f696a2"
down_revision: str | Sequence[str] | None = "2f4be9ced90e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_drops_expires_at"), "drops", ["expires_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_drops_expires_at"), table_name="drops")
    # ### end Alembic commands ###
