"""add index to expires_at

Revision ID: e04bb8f696a2
Revises: 2f4be9ced90e
Create Date: 2026-09-26 22:44:14.920116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04bb8f696a2'
down_revision: Union[str, Sequence[str], None] = '2f4be9ced90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_drops_expires_at'), 'drops', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drops_expires_at'), table_name='drops')
    # ### end Alembic commands ###
